### ISSUE TITLE
Automated Mode : Receiver Functions Checklist

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#274]
The core of YGOPro's gframe is `duelclient.cpp`, it takes a network/replay message and then does a number of actions. Those actions have abritrary data construction specifific to each. The point of `receiver.js` is to **ONLY** extract useful information from the data stream.

Anytime a variable is created within the central case statement, create a new property on the `data`object and save it. Use `BufferIO.ReadInt8()` to act as `BufferIO::ReadInt8(pbuf)` and  `BufferIO.ReadInt32()` to act as `BufferIO::ReadInt32(pbuf)`. Use localPlayer() to act as `mainGame->LocalPlayer()`, and the object `window.duel` or rather `duel` to act as `mainGame`. **NEVER SET VALUES ON `duel`!!!** that is the very problem we are seeking to solve now!

- [x] STOC_ERROR_MSG
- [x] ERRMSG_DECKERROR
- [x] ERRMSG_SIDEERROR
- [x] ERRMSG_VERERROR
- [x] STOC_SELECT_HAND
- [x] STOC_SELECT_TP
- [x] STOC_HAND_RESULT
- [x] STOC_TP_RESULT
- [x] STOC_CHANGE_SIDE
- [x] STOC_WAITING_SIDE
- [x] STOC_JOIN_GAME
- [x] STOC_TYPE_CHANGE
- [x] STOC_DUEL_START
- [x] STOC_DUEL_END
- [x] STOC_REPLAY
- [x] STOC_TIME_LIMIT
- [x] STOC_CHAT
- [x] STOC_HS_PLAYER_ENTER
- [x] STOC_HS_PLAYER_CHANGE
- [x] STOC_HS_WATCH_CHANGE

====
- [x] MSG_RETRY
- [x] MSG_HINT
- [x] HINT_EVENT
- [x] HINT_MESSAGE
- [x] HINT_SELECTMSG
- [x] HINT_OPSELECTED
- [x] HINT_EFFECT
- [x] HINT_RACE
- [x] HINT_ATTRIB
- [x] HINT_CODE
- [x] HINT_NUMBER
- [x] HINT_CARD

=====
- [x] MSG_WIN
- [x] MSG_WAITING
- [x] MSG_START
- [x] MSG_UPDATE_DATA
- [x] MSG_UPDATE_CARD
- [x] MSG_SELECT_BATTLECMD
- [x] MSG_SELECT_IDLECMD
- [x] MSG_SELECT_EFFECTYN
- [x] MSG_SELECT_YESNO
- [x] MSG_SELECT_OPTION
- [x] MSG_SELECT_CARD
- [x] MSG_SELECT_CHAIN
- [x] MSG_SELECT_PLACE MSG_SELECT_DISFIELD
- [x] MSG_SELECT_POSITION
- [x] MSG_SELECT_TRIBUTE
- [x] MSG_SELECT_COUNTER
- [x] MSG_SELECT_SUM
- [x] MSG_SORT_CARD MSG_SORT_CHAIN
- [x] MSG_CONFIRM_DECKTOP
- [x] MSG_CONFIRM_CARDS
- [x] MSG_SHUFFLE_DECK
- [x] MSG_SHUFFLE_HAND
- [x] MSG_REFRESH_DECK
- [x] MSG_SWAP_GRAVE_DECK
- [x] MSG_REVERSE_DECK
- [x] MSG_DECK_TOP
- [x] MSG_SHUFFLE_SET_CARD
- [x] MSG_NEW_TURN
- [x] MSG_NEW_PHASE
- [x] MSG_MOVE
- [x] MSG_POS_CHANGE
- [x] MSG_SET
- [x] MSG_SWAP
- [x] MSG_FIELD_DISABLED
- [x] MSG_SUMMONING
- [x] MSG_SUMMONED
- [x] MSG_SPSUMMONING
- [x] MSG_SPSUMMONED
- [x] MSG_FLIPSUMMONING
- [x] MSG_FLIPSUMMONED
- [x] MSG_CHAINING
- [x] MSG_CHAINED
- [x] MSG_CHAIN_SOLVING
- [x] MSG_CHAIN_SOLVED
- [x] MSG_CHAIN_END
- [x] MSG_CHAIN_NEGATED MSG_CHAIN_DISABLED
- [x] MSG_CARD_SELECTED
- [x] MSG_RANDOM_SELECTED
- [x] MSG_BECOME_TARGET
- [x] MSG_DRAW
- [x] MSG_DAMAGE
- [x] MSG_RECOVER
- [x] MSG_EQUIP
- [x] MSG_LPUPDATE
- [x] MSG_UNEQUIP
- [x] MSG_CARD_TARGET
- [x] MSG_CANCEL_TARGET
- [x] MSG_PAY_LPCOST
- [x] MSG_ADD_COUNTER
- [x] MSG_REMOVE_COUNTER
- [x] MSG_ATTACK
- [x] MSG_BATTLE
- [x] MSG_ATTACK_DISABLED
- [x] MSG_DAMAGE_STEP_START
- [x] MSG_DAMAGE_STEP_END
- [x] MSG_MISSED_EFFECT
- [x] MSG_TOSS_COIN
- [x] MSG_TOSS_DICE
- [x] MSG_ANNOUNCE_RACE
- [x] MSG_ANNOUNCE_ATTRIB
- [x] MSG_ANNOUNCE_CARD
- [x] MSG_ANNOUNCE_NUMBER
- [x] MSG_CARD_HINT
- [x] MSG_MATCH_KILL
- [x] MSG_TAG_SWAP
- [x] MSG_RELOAD_FIELD
