### ISSUE TITLE
Automated Mode : Processor Functions Checklist

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#275]
The core of YGOPro's gframe is `duelclient.cpp`, it takes a network/replay message and then does a number of actions. Those actions have arbitrary data construction specific to each. The point of `processor.js` is to update the internal game model and then trigger UI functionality after the data in the stream has been extracted from 'receiver.js`and fired off via the`network` event emitter.

The events are formulated as such:

``` JavaScript
network.on('NETWORK_MESSAGE', function (data) {
    // do stuff with data;
    // update internal model
    // reply with automated message if needed
    // trigger an animation or GUI update
});
```
- [ ] STOC_ERROR_MSG
- [ ] STOC_SELECT_HAND
- [ ] STOC_SELECT_TP
- [x] STOC_HAND_RESULT
- [ ] STOC_TP_RESULT
- [ ] STOC_CHANGE_SIDE
- [ ] STOC_WAITING_SIDE
- [x] STOC_JOIN_GAME
- [x] STOC_TYPE_CHANGE
- [x] STOC_DUEL_START
- [x] STOC_DUEL_END
- [ ] STOC_REPLAY
- [ ] STOC_TIME_LIMIT
- [ ] STOC_CHAT
- [x] STOC_HS_PLAYER_ENTER
- [x] STOC_HS_PLAYER_CHANGE
- [x] STOC_HS_WATCH_CHANGE
# 
- [x] MSG_RETRY
- [ ] MSG_HINT
- [ ] MSG_WIN
- [x] MSG_WAITING
- [x] MSG_START
- [x] MSG_UPDATE_DATA
- [x] MSG_UPDATE_CARD
- [ ] MSG_SELECT_BATTLECMD
- [ ] MSG_SELECT_IDLECMD
- [ ] MSG_SELECT_EFFECTYN
- [ ] MSG_SELECT_YESNO
- [ ] MSG_SELECT_OPTION
- [ ] MSG_SELECT_CARD
- [ ] MSG_SELECT_CHAIN
- [ ] MSG_SELECT_PLACE MSG_SELECT_DISFIELD
- [ ] MSG_SELECT_POSITION
- [ ] MSG_SELECT_TRIBUTE
- [ ] MSG_SELECT_COUNTER
- [ ] MSG_SELECT_SUM
- [ ] MSG_SORT_CARD MSG_SORT_CHAIN
- [ ] MSG_CONFIRM_DECKTOP
- [ ] MSG_CONFIRM_CARDS
- [x] MSG_SHUFFLE_DECK
- [ ] MSG_SHUFFLE_HAND
- [x] MSG_REFRESH_DECK
- [x] MSG_SWAP_GRAVE_DECK
- [x] MSG_REVERSE_DECK
- [ ] MSG_DECK_TOP
- [ ] MSG_SHUFFLE_SET_CARD
- [ ] MSG_NEW_TURN
- [x] MSG_NEW_PHASE
- [x] MSG_MOVE
- [ ] MSG_POS_CHANGE
- [ ] MSG_SET
- [ ] MSG_SWAP
- [ ] MSG_FIELD_DISABLED
- [ ] MSG_SUMMONING
- [ ] MSG_SUMMONED
- [ ] MSG_SPSUMMONING
- [ ] MSG_SPSUMMONED
- [ ] MSG_FLIPSUMMONING
- [ ] MSG_FLIPSUMMONED
- [ ] MSG_CHAINING
- [ ] MSG_CHAINED
- [ ] MSG_CHAIN_SOLVING
- [ ] MSG_CHAIN_SOLVED
- [ ] MSG_CHAIN_END
- [ ] MSG_CHAIN_NEGATED MSG_CHAIN_DISABLED
- [ ] MSG_CARD_SELECTED
- [ ] MSG_RANDOM_SELECTED
- [ ] MSG_BECOME_TARGET
- [x] MSG_DRAW
- [ ] MSG_DAMAGE
- [ ] MSG_RECOVER
- [ ] MSG_EQUIP
- [ ] MSG_LPUPDATE
- [ ] MSG_UNEQUIP
- [ ] MSG_CARD_TARGET
- [ ] MSG_CANCEL_TARGET
- [ ] MSG_PAY_LPCOST
- [ ] MSG_ADD_COUNTER
- [ ] MSG_REMOVE_COUNTER
- [ ] MSG_ATTACK
- [ ] MSG_BATTLE
- [ ] MSG_ATTACK_DISABLED
- [ ] MSG_DAMAGE_STEP_START
- [ ] MSG_DAMAGE_STEP_END
- [ ] MSG_MISSED_EFFECT
- [ ] MSG_TOSS_COIN
- [ ] MSG_TOSS_DICE
- [ ] MSG_ANNOUNCE_RACE
- [ ] MSG_ANNOUNCE_ATTRIB
- [ ] MSG_ANNOUNCE_CARD
- [ ] MSG_ANNOUNCE_NUMBER
- [ ] MSG_CARD_HINT
- [ ] MSG_MATCH_KILL
- [ ] MSG_TAG_SWAP
- [ ] MSG_RELOAD_FIELD

**Comment by Zayelion** [comment]
Abandoning
