### ISSUE TITLE
Manual System Review

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#300]
# ToDo
- [x] move monster from monster zone to s/t zone
- [x] move monster from deck to s/t zone
- [x] move monster from monster grave to s/t zone
- [x] Opponent triggered `view` of extra deck.
- [x] Opponent triggered `view` of graveyard.
- [ ] move Field to s/t zone
- [x] smooth animation of Extra Deck.
- [x] To Graveyard, to Banished, server side check to go to original controller.
- [x] Prevent Field Zone stacking.
- [x] Set Spells/Traps as monsters from Deck.
- [x] Goblin Circus
- [ ] Convolution of Nature.
- [x] spy-c-spy
- [ ] exchange
- [ ] Rapid click breaks side decking.

**Comment by StormWulf** [comment]
Players are allowed to view their own face-down banished cards

Face-down Attack does need to be a thing, even though it only happens via `Darkness Approaches`

**Comment by Zayelion** [comment]
I think some functionality possibly needs to be added only if a card is 'perceived'.

**Comment by StormWulf** [comment]
There should be a /help command that lists all of the commands to the player, via pop-up perhaps. At the start of each game, the chat should remind players to use the /help command.

**Comment by MorganLeFlaySD** [comment]
LP changes not working,
Can't flip deck over or add/interact with bottom card?
Can't attack yet.
Can't set s/t as monsters (magical hats)
Can't set monsters as s/t (I've been told that artifacts specifically work but not necessarily others)

**Comment by Laughing-Luna** [comment]
- [ ] Banished face-down.

- [ ] Face-down attack position.
- [ ] Placed into opponent's deck.
- [ ] Face-up in a face-down deck.
- [ ] Face-down in a face-up deck.
- [ ] Face-up in opponent's face-down deck.
- [ ] Face-down in oppponent's face-up deck.
- [ ] A "space" to place excavated cards and hand-picked cards that are revealed.  I say space, but just like the banished space, it's NOT a zone.  Just something to differentiate excavated cards from grave and banished.(Useful for things like Spellbook Library of the Crescent and Pot of Duality).  They must also be able to be face-down.
- [ ] Pendulum Monsters face-up in the extra deck must ALWAYS be on top of the monsters face-down in the extra deck.
- [ ] Quality of Life(QoL - optional by default) Nothing for this exists yet, but might as well include a way to flip Extra Deck Pendulum Monsters face-up/down without having to move them from the Extra Deck.
- [ ] A toggle for having card(s) in hand revealed so that they stay that way in addition to the regular reveal.
- [ ] Have another toggle to reveal/hide the entire hand at once.
- [ ] Your cards in the opponent's hand.
- [ ] Attacking while in defense position.
- [ ] QoL: Manually re-arrange cards in hand(this MUST be visible to the opponent), in addition to shuffling the hand.
- [ ] Selection indicator for targetting/selecting cards on the opponent's field and hand.  It MUST persist until the next card is selected.
- [ ] QoL(highly recommended): have the deck automatically shuffle itself after you stop viewing the deck(this must also happen when the opponent looks at your deck)
- [ ] Reveal card(s) from your deck to your opponent without you seeing them(dammit SPYRALs)
- [ ] A way to mark cards that are banished face-down(and face-down "excavated" while we're at it) cards to differentiate them.  This is because Different Dimension Capsule and Pot of Desires and PSY-Frame Overload and a host of other cards all exisit.

**Comment by Zayelion** [comment]
Note from @Salvation-Son-Kun 

- Drawing bug occured again, randomly stops working
- Can't leave game after opponent surrenders
- in the second game, after drawing opening hands, I couldn't open options list for deck or extra deck, but zat could use my deck and extra
zat also can't draw now
Pendulums can't be placed from pendulum zone to face up extra deck
cant view face up cards in opponents extra deck
hovering mouse on a card that was searched (while it is being revealed) didnt make it appear on the left either so i couldnt read it(edited)
cards are revealed to the player that searched them
overlay system is annoying us both
cards in defence mode on opponent field dont fit in monster zones,, probably linked to the scaling issue of the field itself, as well as pendulums and spells/traps being off-centre except in the middle zone(edited)
only turn player should have control of the phases

**Comment by Zayelion** [comment]
Notes from @Laughing-Luna 

- I have a Pendulum Synchro Monster in my hand... And a Metalfoe Pendulum facedown in my extra
And I can't summon the Pend-synchro from hand Once a Pendulum/Extra Deck monster is out of the extra deck, you can't get it face-up in the extra again.  Once it leaves the field to be banished or in the grave or hand, you can't get it on the field anymore Wait, ammending the last one - Pend/Xyz can be summoned just fine.

- I'm assuming putting stuff in the opponent's grave is to emulate an anime effect?
- Players need to be able to view their own banished face-down cards
- We can stack field spells into the field zone.  Either have it send the previous to the grave, or make the new one unable to go to the field zone without first sending the one there to the grave
- And I assume overlaying is a work in progress
- I cannot view my opponent's grave
- Activating/setting/summoning from deck checks out.
- Cards need to be able to from monster zone/hand to s/t zone(edited)
- We need to be able to view the opponent's face-up extra deck
- Oh!  Also, face-down attack position needs to be a thing.
- Adding/subbing LP is not working.
- When one goes to x out the launcher, make it auto-surrender them, not lock them.
# Notes
- My own testing shows that LP adding and subtracting works fine. 
- Face-Down attack doesnt need to be a thing.
- I need a ruling on viewing Facedowns removed.

**Comment by Zayelion** [comment]
Closing Starting a new notes.
