### ISSUE TITLE
Card Tracking List

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#341]
## TCG Spoiler `100912XXX`
- [x] [MACR-EN] SPYRAL Gear – Fully Armed
- [ ] [MACR-EN] SPYRAL Mission - Rescue

## Structure Deck: Cyberse Link `100332XXX`
- [ ] Trigate Wizard
- [ ] Binal Sorceress
- [ ] Dual Assembloom
- [ ] ROM Cloudia
- [ ] Balancer Lord
- [ ] Dot Scaper

## Duelist Pack: Legend Duelist `100418XXX`
- [x] Red-Eyes Slash Dragon
- [x] Red-Eyes Baby Dragon
- [x] Red-Eyes Metal Knight Gearfried
- [x] Red-Eyes Fang with Chain
- [x] Amazoness Princess
- [x] Amazoness Pet Baby Tiger
- [x] Amazoness Call
- [x] Amazoness Ambush
- [x] Stronghold Whale
- [x] The Legendary Fisherman II
- [x] Rage of Kairyun-Shin
- [x] Sea Stealth Attack

## Collector’s Pack 2017 `100217XXX`
- [ ] Sadion, the Timelord
- [ ] Zaphion, the Timelord
- [ ] Camion, the Timelord
- [ ] Giant Rex
- [ ] Spacetime Transcendence
- [ ] Ultimate Evolution Pill
- [x] Number 89: Computerbeast Diablosis
- [x] Number 68: Fiendish Skyprison Sandalfon
- [x] Number 71: Lebarian Shark
- [X] White Moray
- [X] White Aura Dolphin
- [X] White Aura Whale
- [ ] Amazoness Spy
- [ ] Vision HERO Witch Raider

## Promos and Misc
- [x] D/D/D Superdoom King Purplish Armageddon `100219002`
- [X] Odd-Eyes Wing Dragon `100219001`
