### ISSUE TITLE
SDY script tracking list

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#373]
# SDY
## Asterisks indicate alternate art
- [ ] The Stern Mystic [87557188]
- [ ] Wall of Illusion [13945283]
- [ ] Trap Master [46461247]
- [ ] Card Destruction [72892473]
- [ ] Change of Heart [4031928]
- [ ] De-Spell [19159413]
- [ ] Dian Keto the Cure Master [84257639]*
- [ ] Last Will [85602018]
- [ ] Soul Exchange [68005187]
- [ ] Sword of Dark Destruction [37120512]
- [ ] Castle Walls [44209392]
- [ ] Reinforcements [17814387]
- [ ] Reverse Trap [77622396]
- [ ] Waboku [12607053]
- [ ] Ultimate Offering [80604091]*
