### ISSUE TITLE
SDK script tracking list

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#374]
# SDK
- [ ] Lord of D. [17985575]
- [ ] Mysterious Puppeteer [54098121]
- [ ] The Wicked Worm Beast [6285791]
- [ ] Ancient Telescope [17092736]
- [ ] Ookazi [19523799]
- [ ] The Flute of Summoning Dragon [43973174]
- [ ] The Inexperienced Spy [81820689]
- [ ] Invigoration [98374133]
- [ ] Just Desserts [24068492]
