### ISSUE TITLE
LOB script tracking list

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOPro-Salvation-Server#375]
# LOB 
## Asterisks indicate alternate arts required
- [x] Reaper of the Cards [33066139]
- [x] Exodia the Forbidden One [33396948]
- [x] Man-Eater Bug [54652250]
- [x] Hane-Hane [7089711]
- [x] Armed Ninja [9076207]
- [x] Gaia the Dragon Champion [66889139]
- [ ] Metal Dragon [9293977]
- [x] Flame Swordsman [45231177]
- [ ] Flower Wolf [95952802]
- [x] Darkfire Dragon [17881964]
- [ ] Karbonala Warrior [54541900]
- [ ] Dragoness the Wicked Knight [70681994]
- [x] Charubin the Fire Knight [37421579]
- [x] Flame Ghost [58528964] 
- [x] Fusionist [1641882]
- [x] Dark Hole [53129443]
- [ ] Final Flame [73134081]*
- [ ] Fissure [66788016]
- [ ] Goblin's Secret Remedy [11868825]
- [ ] Gravedigger Ghoul [82542267]
- [ ] Hinotama [46130346]
- [ ] Monster Reborn [83764718]*
- [ ] Polymerization [24094653]*
- [ ] Pot of Greed [55144522]
- [ ] Raigeki [12580477]
- [ ] Red Medicine [38199696]
- [ ] Remove Trap [51482758]
- [ ] Sparks [76103675]
- [ ] Stop Defense [63102017]
- [ ] Swords of Revealing Light [72302403]
- [ ] Beast Fangs [46009906]
- [ ] Book of Secret Arts [91595718]
- [ ] Dark Energy [4614116]
- [ ] Dragon Treasure [1435851]
- [ ] Electro-Whip [37820550]
- [ ] Follow Wind [98252586]
- [ ] Laser Cannon Armor [77007920]
- [x] Legendary Sword [61854111]
- [ ] Machine Conversion Factory [25769732] 
- [ ] Mystical Moon [36607978]
- [ ] Power of Kaishin [77027445]
- [ ] Raise Body Heat [51267887]
- [ ] Silver Bow and Arrow [1557499]
- [ ] Vile Germs [39774685]
- [ ] Violet Crystal [15052462]
- [ ] Forest [87430998]
- [ ] Mountain [50913601]
- [ ] Sogen [86318356]
- [ ] Umi [22702055]
- [ ] Wasteland [23424603]
- [ ] Yami [59197169]
- [ ] Trap Hole [4206964]
- [ ] Two-Pronged Attack [83887306]
- [ ] Dragon Capture Jar [50045299]
